### Q.10. Analysis the performance of ANN when the value of learning rate, epoch, no of hidden layer and neurons of hidden layer change in ANN.
#### a. Consider the trained model of earlier experiment, change the value of learning rate, and evaluate the performance.
#### b. Similarly, change the value of epoch, no of hidden layer and neurons of hidden layer and evaluate the performance.
#### c. Evaluate the performance when the value of learning rate, epoch, no of hidden layer and neurons of hidden layer are changed. Analysis the performance and plot graph of performance/analysis for better understanding

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
# label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
# One hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### ANN

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [17]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.01), loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'mse', metrics = ['accuracy'])

In [19]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'mae', metrics = ['accuracy'])

In [20]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'mape', metrics = ['accuracy'])

In [21]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'msle', metrics = ['accuracy'])

In [22]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'squared_hinge', metrics = ['accuracy'])

In [23]:
#ann.compile(optimizer = tf.keras.optimizers.Adam (learning_rate=0.001), loss = 'hinge', metrics = ['accuracy'])

In [24]:
history =ann.fit(X_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.2234 - accuracy: 0.7099
Epoch 2/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1578 - accuracy: 0.8008
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1454 - accuracy: 0.8036
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1415 - accuracy: 0.8083
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1390 - accuracy: 0.8110
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1368 - accuracy: 0.8114
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1347 - accuracy: 0.8163
Epoch 8/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1326 - accuracy: 0.8226
Epoch 9/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1309 - accuracy: 0.8239
Epoch 10/20
250/250 [==============================] - 1s 2ms/step - loss: 0.1297 - accuracy: 0.8259

### Predicting the Test set results

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 208  197]]


0.8585